name: CD
on:
  release:
    types: [published, edited]

jobs:
  CD:
    name: Langevin on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest, ubuntu-latest, macos-14]
    steps:
      - uses: actions/checkout@v4

      - name: setup graalvm for static native build
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: 'native-image'
          native-image-musl: 'true'
          native-image-job-reports: 'true'
        if: matrix.os == 'ubuntu-latest'

      - name: setup graalvm for non-static build
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
        if: matrix.os == 'macos-13' || matrix.os == 'macos-14' || matrix.os == 'windows-latest'

      - name: java build and test
        run: mvn test
        if: matrix.os == 'macos-13'|| matrix.os == 'macos-14'  || matrix.os == 'windows-latest'

      - name: static native build without test - linux only
        run: mvn -Pnative-static -DskipTests=true package
        if: matrix.os == 'ubuntu-latest'

      - name: non-static native build without test - macos or windows
        run: mvn -Pnative -DskipTests=true package
        if: matrix.os == 'macos-13'|| matrix.os == 'macos-14'  || matrix.os == 'windows-latest'

      - name: run native executable with --help option to verify build (zero return code)
        run: ./target/langevin --help

      - name: Upload MacOS or Linux solver binary to release assets
        if: github.event_name == 'release' && (matrix.os == 'macos-13' || matrix.os == 'macos-14' || matrix.os == 'ubuntu-latest')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/langevin
          asset_name: langevin-${{ matrix.os }}
          asset_content_type: application/octet-stream

      - name: Upload Windows solver binary to release assets
        if: github.event_name == 'release' && matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/langevin.exe
          asset_name: langevin-${{ matrix.os }}
          asset_content_type: application/octet-stream

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
